name: seerbit_flutter_native
description: Seerbit Flutter Package.
version: 0.0.1+2
homepage: https://github.com

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.10.2
  pinput: ^2.2.21
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  animate_do: ^3.0.2
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  http: ^0.13.5
  lottie: ^1.4.2
  webview_flutter: ^4.0.2
  validatorless: ^1.2.3
  google_fonts: ^4.0.3
  pattern_formatter: ^2.0.0
  pointycastle: ^3.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/success.json
    - assets/
    - assets/seerbit.png
  fonts:
    - family: FaktPro
      fonts:
        - asset: assets/fonts/FaktProNormal.otf
          style: normal
